### ISSUE TITLE
Handle click and swipe events

### ISSUE THREAD

**Issue by pacien** [pacien/pointless-viewer#9]
Navigate between slides on mouse click and swipe gestures, in addition to arrow keys.

**Comment by pacien** [comment]
Implemented with commit 4ac79e4.

**Comment by ztchan** [comment]
Is it possible to add clicker support? Seems like we can't navigate between slides with a clicker.

**Comment by pacien** [comment]
@ztchan wrote:
> Is it possible to add clicker support? Seems like we can't navigate between slides with a clicker.

Most clickers/remotes that emulate a left, right, space, or enter key press or left/right click should already be supported. With those, one just needs to focus the cursor in the browser's window, and everything should work as usual.
